openapi: 3.0.0
info:
  title: workshop
  version: '1.0'
  description: API for an app we build as part of the flask workshop.
servers:
  - url: 'http://localhost:5000'
paths:
  '/movies/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-movies
      description: Lists all movies
    post:
      summary: ''
      operationId: post-movies
      responses:
        '200':
          description: OK
      description: Takes selected movie and maps it to the current user.
    put:
      summary: ''
      operationId: put-movies
      responses:
        '200':
          description: OK
      description: Adds movie to database
    delete:
      summary: ''
      operationId: delete-movies
      responses:
        '200':
          description: OK
      description: Removes movie from the database
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-users-id
      description: Get list of users
    put:
      summary: ''
      operationId: put-users-id
      responses:
        '200':
          description: OK
      description: Adds a user
components:
  schemas:
    Movie:
      title: Movie
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
          minLength: 1
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        '':
          type: string
